### ISSUE TITLE
README.md typo

### ISSUE THREAD

**Issue by spences10** [MarcL/amazon-product-server#3]
Missed the s in should?

![typo image](https://user-images.githubusercontent.com/234708/34295977-116e1614-e708-11e7-9cd6-2fd9cd46c0a4.png)

**Comment by MarcL** [comment]
Yes - you're right. Good spot. Will fix it @spences10.
Doing a PR on this soon as I'm refactoring to properly support all locales.

**Comment by spences10** [comment]
Stale, closing
